version: '3.9'
services:
  db:
    image: postgres:16
    env_file:
      - .env.prod
    volumes:
      - db_data_prod:/var/lib/postgresql/data
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.prod
    ports:
      - '80:8000'
    depends_on:
      - db
volumes:
  db_data_prod: