version: '3.9'

services:
  db:
    image: postgres:16
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    env_file:
      - .env.prod
    expose:
      - "8000"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
